/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a post by ID */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /** Delete a post */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a feed */
        post: operations["createFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a feed by ID */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow a feed */
        post: operations["followFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{id}/unfollow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unfollow a feed */
        post: operations["unfollowFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a post to a feed */
        post: operations["submitToFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a public profile */
        get: operations["getProfile"];
        /** Update a public profile */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search user profiles */
        post: operations["searchProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a comment on a post */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments for a post */
        get: operations["listComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search entities */
        post: operations["searchEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a session cookie */
        post: operations["verifySession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version information */
        get: operations["versionCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Timestamps: {
            createdAt: string;
            updatedAt: string;
        };
        EntityStats: {
            viewers: number;
            followers: number;
            sharers: number;
            likers: number;
            comments: number;
            views: number;
            reposts: number;
            quotes: number;
            annotations: number;
            tags: number;
        };
        ContentEntityProperties: {
            displayName: string;
            mainContent: string;
            tags: string[];
            mentions: string[];
        };
        FeedProperties: components["schemas"]["ContentEntityProperties"] & {
            rules: string[];
        };
        SearchEntityRefs: {
            hasOwner: string[];
            hasViewer: string[];
            hasEditPermissions: string[];
            hasArchivePermissions: string[];
            hasUpdateViewersPermissions: string[];
            hasConfigurePropertiesPermissions: string[];
        };
        ContentEntityRefs: components["schemas"]["SearchEntityRefs"] & {
            hasFollower: string[];
            hasSharer: string[];
            hasTag: string[];
            hasMention: string[];
            hasLiker: string[];
            hasSecretLiker: string[];
            hasAnonymousLiker: string[];
            hasReviewer: string[];
            hasCreator: string[];
            hasBeenViewedBy: string[];
            hasFlair: string[];
            hasSupporter: string[];
            hasComments: string[];
            hasCommenter: string[];
            hasQuote: string[];
            hasQuoter: string[];
            hasAnnotation: string[];
            hasAnnotator: string[];
            hasRepost: string[];
            hasReposter: string[];
            hasAuthor: string[];
            hasCollaborator: string[];
            hasRelated: string[];
        };
        FeedEntityRefs: components["schemas"]["ContentEntityRefs"] & {
            hasModerator: string[];
            hasMember: string[];
            hasApprover: string[];
            hasSubmitPermissions: string[];
            hasConfigureBehaviorPermissions: string[];
            hasSubmission: string[];
            hasRejected: string[];
        };
        FeedBehavior: {
            submissionModels: string[];
            approvalModels: string[];
            aggregationRules?: {
                [key: string]: unknown;
            }[];
            ownershipModels: string[];
            automatedRules: string[];
            contentModel: string[];
            flair: string[];
        };
        PostMedia: {
            url: string;
            /** @enum {string} */
            type: "image" | "video" | "audio" | "document";
            caption?: string;
            altText?: string;
        };
        CreatePostDto: {
            title: string;
            content: string;
            tags?: string[];
            mentions?: string[];
            isPublic?: boolean;
            media?: components["schemas"]["PostMedia"][];
        };
        DbPost: {
            id: string;
            /** @enum {string} */
            type: "post";
            name: string;
            search: string;
            refs: components["schemas"]["ContentEntityRefs"];
            isPublic: boolean;
            isPublished: boolean;
            timestamps: components["schemas"]["Timestamps"];
            metadata: {
                [key: string]: unknown;
            };
            stats: components["schemas"]["EntityStats"];
            properties: components["schemas"]["ContentEntityProperties"];
        };
        PostViewModel: {
            id: string;
            title: string;
            content: string;
            authorId: string;
            authorUsername: string;
            authorDisplayName: string;
            authorAvatarUrl: string;
            tags: string[];
            mentions: string[];
            media: components["schemas"]["PostMedia"][];
            isPublic: boolean;
            isPublished: boolean;
            stats: components["schemas"]["EntityStats"];
            timestamps: components["schemas"]["Timestamps"];
            canEdit: boolean;
            canDelete: boolean;
            isLiked: boolean;
            isFollowing: boolean;
            isOwner: boolean;
        };
        CreateFeedDto: {
            name: string;
            description: string;
            /** @enum {string} */
            subtype: "user" | "feed" | "dynamic" | "list" | "board";
            rules?: string[];
            tags?: string[];
            isPublic?: boolean;
            parentFeed?: string;
            submissionModels?: string[];
            approvalModels?: string[];
            ownershipModels?: string[];
        };
        DbFeed: {
            id: string;
            /** @enum {string} */
            type: "feed";
            name: string;
            search: string;
            /** @enum {string} */
            subtype: "user" | "feed" | "dynamic" | "list" | "board";
            parentFeed?: string;
            childrenFeeds: string[];
            refs: components["schemas"]["FeedEntityRefs"];
            isPublic: boolean;
            isPublished: boolean;
            timestamps: components["schemas"]["Timestamps"];
            metadata: {
                [key: string]: unknown;
            };
            stats: components["schemas"]["EntityStats"];
            properties: components["schemas"]["FeedProperties"];
            behavior: components["schemas"]["FeedBehavior"];
        };
        FeedViewModel: {
            id: string;
            name: string;
            description: string;
            /** @enum {string} */
            subtype: "user" | "feed" | "dynamic" | "list" | "board";
            rules: string[];
            isPublic: boolean;
            isPublished: boolean;
            stats: components["schemas"]["EntityStats"];
            timestamps: components["schemas"]["Timestamps"];
            parentFeed?: string;
            childrenFeeds: string[];
            behavior: components["schemas"]["FeedBehavior"];
            isOwner: boolean;
            isModerator: boolean;
            isMember: boolean;
            isFollowing: boolean;
            canPost: boolean;
            canModerate: boolean;
        };
        PublicProfile: {
            uid: string;
            username: string;
            displayName: string;
            bio: string;
            avatarUrl: string;
            coverImageUrl?: string;
            location?: string;
            website?: string;
            isVerified: boolean;
            followerCount: number;
            followingCount: number;
            postCount: number;
            timestamps: components["schemas"]["Timestamps"];
        };
        ProfileFormData: {
            displayName?: string;
            bio?: string;
            avatarUrl?: string;
            coverImageUrl?: string;
            location?: string;
            website?: string;
            username?: string;
        };
        Comment: {
            id: string;
            postId: string;
            authorId: string;
            authorUsername: string;
            authorDisplayName: string;
            authorAvatarUrl: string;
            content: string;
            timestamps: components["schemas"]["Timestamps"];
            replyCount: number;
            likeCount: number;
            isLiked: boolean;
            canEdit: boolean;
            canDelete: boolean;
        };
        PaginatedCommentResult: {
            items: components["schemas"]["Comment"][];
            total: number;
            page: number;
            limit: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
            nextCursor?: string;
        };
        AlgoliaSearchParams: {
            query: string;
            page?: number;
            hitsPerPage?: number;
            filters?: string;
            facetFilters?: string[][];
            attributesToRetrieve?: string[];
            attributesToHighlight?: string[];
            highlightPreTag?: string;
            highlightPostTag?: string;
            aroundLatLng?: string;
            aroundRadius?: number;
            typoTolerance?: boolean | ("min" | "strict");
        };
        SearchResultItem: {
            objectID: string;
            /** @enum {string} */
            type: "post" | "feed" | "comment" | "feed_submission";
            name: string;
            search: string;
            isPublic: boolean;
            timestamps: components["schemas"]["Timestamps"];
            _highlightResult?: {
                [key: string]: components["schemas"]["HighlightResult"];
            };
        };
        HighlightResult: {
            value: string;
            /** @enum {string} */
            matchLevel: "none" | "partial" | "full";
            matchedWords: string[];
        };
        VerifySessionResult: {
            uid: string;
            claims: {
                [key: string]: unknown;
            };
        };
        CustomClaims: {
            isOwnerOf?: string[];
            isOverseerOf?: string[];
        } & {
            [key: string]: unknown;
        };
        HealthCheckResponse: {
            /** @example ok */
            status: string;
            /** Format: date-time */
            timestamp: string;
        };
        VersionResponse: {
            /** @example 0.2.0 */
            version: string;
            /** @example production */
            environment: string;
        };
        SdkError: {
            /**
             * @description Machine-readable error code
             * @enum {string}
             */
            code: "NOT_FOUND" | "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "CONFLICT" | "EXTERNAL_SERVICE_ERROR" | "RATE_LIMIT" | "INTERNAL_ERROR" | "NOT_IMPLEMENTED";
            /** @description Human-readable error message */
            message: string;
            /** @description HTTP status code */
            status: number;
            /** @description Additional error context */
            context?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description External service error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
        /** @description Endpoint not yet implemented */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SdkError"];
            };
        };
    };
    parameters: {
        /** @description Authenticated user's Firebase UID */
        UserId: string;
        /** @description Resource identifier */
        ResourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPost: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description Post created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbPost"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostViewModel"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    createFeed: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedDto"];
            };
        };
        responses: {
            /** @description Feed created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbFeed"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedViewModel"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    followFeed: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed followed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    unfollowFeed: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed unfollowed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    submitToFeed: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    postId: string;
                };
            };
        };
        responses: {
            /** @description Post submitted to feed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Firebase UID of the profile owner */
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Firebase UID of the profile owner */
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileFormData"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchProfiles: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    limit?: number;
                };
            };
        };
        responses: {
            /** @description Matching profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"][];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    postId: string;
                    content: string;
                };
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listComments: {
        parameters: {
            query?: {
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Number of comments to return */
                limit?: number;
            };
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCommentResult"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path: {
                /** @description Resource identifier */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    searchEntities: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated user's Firebase UID */
                "x-user-id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlgoliaSearchParams"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultItem"][];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
        };
    };
    verifySession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessionCookie: string;
                };
            };
        };
        responses: {
            /** @description Session is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifySessionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    versionCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
